# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изделия')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('desired_deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('deleted', 'Удалена')], default='new', max_length=20, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='clients.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за единицу')),
                ('material_source', models.CharField(choices=[('customer', 'Заказчик'), ('waste', 'Отходы'), ('purchase', 'Закупка')], max_length=50, verbose_name='Источник материала')),
                ('accepted_date', models.DateField(verbose_name='Дата принятия')),
                ('planned_completion_date', models.DateField(verbose_name='Плановая дата сдачи')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='Дата запуска')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('in_progress', 'В производстве'), ('completed', 'Завершён'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.customer', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='directories.product', verbose_name='Изделие')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
