# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Показания счётчика')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='directories.equipment', verbose_name='Оборудование')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='directories.operationtype', verbose_name='Тип операции')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
