# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='directories.expensecategory', verbose_name='Категория расходов')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('prepayment', 'Предоплата'), ('final_payment', 'Итоговая оплата'), ('other', 'Прочее')], max_length=20, verbose_name='Тип платежа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
    ]
