# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='Дата смены')),
                ('efficiency_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Оценка эффективности')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Табель смены',
                'verbose_name_plural': 'Табели смен',
                'unique_together': {('employee', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to='orders.order', verbose_name='Заказ')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to='directories.workcategory', verbose_name='Категория работ')),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='worklog.worklog', verbose_name='Табель')),
            ],
            options={
                'verbose_name': 'Запись работы',
                'verbose_name_plural': 'Записи работ',
            },
        ),
    ]
