# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('passport_number', models.CharField(max_length=10, unique=True, verbose_name='Номер паспорта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contract_number', models.CharField(max_length=8, unique=True, verbose_name='Номер трудового договора')),
                ('hire_date', models.DateField(verbose_name='Дата приёма')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('status', models.CharField(choices=[('hired', 'Нанят'), ('dismissed', 'Уволен')], default='hired', max_length=20, verbose_name='Статус')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directories.position', verbose_name='Должность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directories.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_links', to='directories.competence', verbose_name='Компетенция')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_links', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Компетенция сотрудника',
                'verbose_name_plural': 'Компетенции сотрудников',
                'unique_together': {('employee', 'competence')},
            },
        ),
    ]
