# Generated by Django 6.0.6 on 2026-06-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID сущности')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('file_category', models.CharField(choices=[('drawing', 'Чертёж'), ('contract', 'Договор'), ('model', '3D-модель'), ('program', 'Управляющая программа'), ('report', 'Отчёт'), ('payment', 'Платёжный документ'), ('hr', 'Кадровый документ'), ('equipment', 'Паспорт оборудования'), ('other', 'Прочее')], max_length=50, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип сущности')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='files_file_content_20a48a_idx')],
            },
        ),
    ]
